server:
  port: 8084

spring:
  application:
    name: mall-canal
  cloud:
    nacos:
      config:
        file-extension: yml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848

canal:
  server: 127.0.0.1:11111
  destination: example
logging:
  pattern:
    console: "%msg%n"
  level:
    root: info