server:
  port: 8085
spring:
  application:
    name: mall-search-web
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    encoding: utf-8
logging:
  pattern:
    console: "%msg%n"
  level:
    root: info